/***
 * 
 * FAZER TODA A PARTE DE LOGICA DE API AQUI PARA O NOVO 
 * METODO DE PERMISSIONAMENTO DAS APIS
 * 
 * POR GENTELIZA SEGUIR A SEGUINTE ESTRUTURA
 * 
 * 
 * API E CHAMADA -> PASSA POR AQUI, ELA PEGA NO BD QUAIS AS PERMISSIONS E REENVIA A AUTORIZAÇÃO
 * DO CONTRARIO, ELA PARA AQUI E JOGA 409 FORBIDDEN
 * DESTA FORMA EU PEGO 
 * 
 * ROLE
 * RESOURCE 
 * PERMISSION 
 * 
 * DENTRO DO BD AQUI NESTE ARQUIVO E JOGO TRES RETORNOS RETORNOS DIFERENTES: PERMISSOES, AUTORiZACAO E DINIMICIDADE
 * 
 * POR GENTELIZA, MANTER ESTE CODIGO LIMPO E ORGANIZADO 
 */


function autoAuthorize(resourceName) {
    return (req, res, next) => {
        
    }
}